import 'dotenv/config';
import express from 'express';
import cors from 'cors';
import helmet from 'helmet';
import morgan from 'morgan';
import path from 'path';
import { fileURLToPath } from 'url';
import chatRouter from './chat-route.js';
import leadsRouter from './leads-route.js';
import whatsappRouter from './whatsapp-route.js';
import adminRouter from './admin-route.js';
import { business } from './business-config.js';
const app = express();
const __dirname = path.dirname(fileURLToPath(import.meta.url));
app.use(helmet({ contentSecurityPolicy: false }));
app.use(cors());
app.use(express.json({ limit: '1mb' }));
app.use(morgan('tiny'));
app.get('/api/health', (_req, res) => res.json({ ok: true, app: 'Adil AI OS', version: '1.0.1' }));
app.get('/api/business', (_req, res) => res.json(business));
app.use('/api/chat', chatRouter);
app.use('/api/leads', leadsRouter);
app.use('/api/whatsapp', whatsappRouter);
app.use('/api/admin', adminRouter);
app.use(express.static(__dirname));
app.get('*', (_req, res) => res.sendFile(path.join(__dirname, 'index.html')));
app.use((err, _req, res, _next) => { console.error(err); res.status(500).json({ error: 'Server error' }); });
const port = Number(process.env.PORT || 3000);
app.listen(port, '0.0.0.0', () => console.log(`Adil AI OS running on port ${port}`));
